image:
  repository: eu.gcr.io/my-new-project-467616/kuber_practice_app
  digest: sha256:2bf1ef8505ca48ff5fd039b45b59edf1ed15c1b686ccfa5b52394d9f52644011
  pullPolicy: IfNotPresent

cronJobImage:
  repository: eu.gcr.io/my-new-project-467616/kuber_practice_app_redis
  digest: sha256:084c2ed5796a8b491a629335dfa96d360ce5242d6bfafccfe605dc61066645fc
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 8080

postgres:
  host: set_in_terraform_helm_config
  user: set_in_terraform_helm_config
  password: set_in_terraform_helm_config
  db: set_in_terraform_helm_config

redis:
  host: set_in_terraform_helm_config
  password: set_in_terraform_helm_config

api_key: set_in_terraform_helm_config