image:
  repository: eu.gcr.io/my-new-project-467616/kuber_practice_app
  digest: set_in_terraform_helm_config
  pullPolicy: IfNotPresent

cronJobImage:
  repository: eu.gcr.io/my-new-project-467616/kuber_practice_app_redis
  digest: set_in_terraform_helm_config
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 8080

postgres:
  host: set_in_terraform_helm_config
  user: set_in_terraform_helm_config
  password: set_in_terraform_helm_config
  db: set_in_terraform_helm_config

redis:
  host: set_in_terraform_helm_config
  password: set_in_terraform_helm_config

api_key: set_in_terraform_helm_config