image:
  repository: eu.gcr.io/my-new-project-467616/kuber_practice_app
  digest: sha256:3f61cad25440fc667a0211f2073166c0dd619b98a9e1a9f5a43efb2c88a4129a
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 8080