apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-practice-app-service-config
data:
  PORT: "8080"
  POSTGRES_USER: "kuber_practice_user"
  POSTGRES_HOST: "172.20.0.3"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kuber_practice"
  MIGRATIONS_DIRECTORY: "/app/db/migrations"
  REDIS_HOST: "10.153.136.179:6379"
