apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-practice-app-service-config
data:
  PORT: "8080"
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
  MIGRATIONS_DIRECTORY: "/app/db/migrations"
  REDIS_HOST: "{{ .Values.redis.host }}:6379"
