apiVersion: v1
kind: Secret
metadata:
  name: kuber-practice-app-secrets
data:
  postgres_password: {{ .Values.postgres.password | b64enc}}
  api_key: "{{ .Values.api_key | b64enc }}"
  redis_password: "{{ .Values.redis.password | b64enc }}"
