// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        pgtype.UUID
	Name      string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}
