// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package dbmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const addFile = `-- name: AddFile :execresult
INSERT INTO files(name, content)
VALUES($1, $2)
`

type AddFileParams struct {
	Name    string
	Content string
}

func (q *Queries) AddFile(ctx context.Context, arg AddFileParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, addFile, arg.Name, arg.Content)
}

const listFiles = `-- name: ListFiles :many
SELECT id, name, content, created_at, updated_at FROM files
ORDER BY name
LIMIT 2
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
